In [2]:
import numpy as np
import pandas as pd

In [6]:
arr1 = np.array([[1,2,3],[2,4,6]])
arr2 = np.array([[4,-1],[-5, -8],[4,5]])
print(arr1)
print(arr2)

[[1 2 3]
 [2 4 6]]
[[ 4 -1]
 [-5 -8]
 [ 4  5]]


In [5]:
randomarray = np.random.rand(2,2)
print(randomarray)

[[0.65646532 0.36589494]
 [0.91617219 0.28319272]]


In [8]:
flavor1 = np.dot(arr1, arr2)
print(flavor1)
flavor3 = arr1 @ arr2
print(flavor3)

[[ 6 -2]
 [12 -4]]
[[ 6 -2]
 [12 -4]]


In [16]:
res = np.zeros((arr1.shape[0], arr2.shape[1]))

for i in range(len(arr1)): 
  for j in range(len(arr2[0])): 
    for k in range(len(arr2)): 
      res[i][j] += arr1[i][k] * arr2[k][j]
 
print(res)

[[ 6. -2.]
 [12. -4.]]


In [17]:
meanarr1 = np.mean(arr1)
print(meanarr1)

3.0


In [28]:
data = pd.read_csv(r"C:\Users\brijesh\Downloads\062_BrijeshKhunt\lab1\mtcars.csv")
del data['model']
meancenter = data.apply(lambda e: e - e.mean())
print(meancenter.head())

        mpg     cyl        disp       hp      drat       wt     qsec      vs  \
0  0.909375 -0.1875  -70.721875 -36.6875  0.303437 -0.59725 -1.38875 -0.4375   
1  0.909375 -0.1875  -70.721875 -36.6875  0.303437 -0.34225 -0.82875 -0.4375   
2  2.709375 -2.1875 -122.721875 -53.6875  0.253437 -0.89725  0.76125  0.5625   
3  1.309375 -0.1875   27.278125 -36.6875 -0.516563 -0.00225  1.59125  0.5625   
4 -1.390625  1.8125  129.278125  28.3125 -0.446563  0.22275 -0.82875 -0.4375   

        am    gear    carb  
0  0.59375  0.3125  1.1875  
1  0.59375  0.3125  1.1875  
2  0.59375  0.3125 -1.8125  
3 -0.40625 -0.6875 -1.8125  
4 -0.40625 -0.6875 -0.8125  
